dist: xenial

language: python
python:
    - "3.7"
install:
    - "pip install -r requirements.txt"

script:
    - "nosetests tests --nocapture --nologcapture --with-coverage --cover-erase --cover-inclusive --cover-erase --cover-package ."
    - "coverage report -mi"
after_success:
    - coveralls
